kafka:
  oppgave:
    topic: 'privat-eessipensjon-oppgave-v1'
    groupid: 'eessi-pensjon-group'

#Spring
spring:
  kafka:
    listener:
      ack-mode: manual
    consumer:
      enable-auto-commit: false
      key-deserializer: 'org.apache.kafka.common.serialization.StringDeserializer'
#      value-deserializer: 'org.springframework.kafka.support.serializer.JsonDeserializer'
    bootstrap-servers: '${KAFKA_BOOTSTRAP_SERVERS_URL}'
    properties:
      spring.json.trusted.packages: '*'
      security.protocol: 'SASL_SSL'
      value.subject.name.strategy: 'io.confluent.kafka.serializers.subject.TopicRecordNameStrategy'
      sasl:
        mechanism: 'PLAIN'
        jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username="${srvusername}" password="${srvpassword}";

securityTokenService:
  discoveryUrl: ${SECURITY_TOKEN_SERVICE_OPENID_CONFIGURATION_URL}

eessi-topic: ${kafka.oppgave.topic}-${FASIT_ENVIRONMENT_NAME}

#Metrics
#management:
#  endpoints:
#    metrics.enabled: true
#    web.exposure.include: '*'
#    export.prometheus.enabled: true
#    prometheus.enabled: true

management:
  metrics:
    export:
      prometheus:
        enabled: true
  endpoints:
    web:
      exposure:
        include: info, health, metrics, prometheus
  endpoint:
    info:
      show-details: "ALWAYS"

no.nav.orgnummer: 889640782