kafka:
  security.protocol: SSL
  oppgave:
    topic: ${KAFKA_OPPGAVE_TOPIC}
    groupid: 'eessi-pensjon-group'
  oppdater-oppgave:
    topic: ${KAFKA_OPPDATER_OPPGAVE_TOPIC}
    groupid: 'eessi-pensjon-group'


no.nav.security.jwt:
  client:
    registration:
      oppgave-credentials:
        token-endpoint-url: ${AZURE_OPENID_CONFIG_TOKEN_ENDPOINT}
        grant-type: client_credentials
        scope: api://${OPPGAVE_CLIENT_ID}/.default
        authentication:
          client-id: ${AZURE_APP_CLIENT_ID}
          client-jwk: ${AZURE_APP_JWK}
          client-auth-method: private_key_jwt
      saf-credentials:
        token-endpoint-url: ${AZURE_OPENID_CONFIG_TOKEN_ENDPOINT}
        grant-type: client_credentials
        scope: api://${AZURE_APP_SAF_CLIENT_ID}/.default
        authentication:
          client-id: ${AZURE_APP_CLIENT_ID}
          client-jwk: ${AZURE_APP_JWK}
          client-auth-method: private_key_jwt

securityTokenService:
  discoveryUrl: ${SECURITY_TOKEN_SERVICE_OPENID_CONFIGURATION_URL}

METRICS_REQUESTFILTER_ENABLE: true

#Metrics
management:
  metrics:
    export:
      prometheus:
        enabled: true
  endpoints:
    web:
      exposure:
        include: info, health, metrics, prometheus
  endpoint:
    info:
      show-details: "ALWAYS"

no.nav.orgnummer: 889640782