kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: eessi-pensjon-oppgave-q1
  namespace: eessipensjon
  labels:
    team: eessipensjon
spec:
  kafka:
    pool: nav-dev
  envFrom:
    - secret: eessi-pensjon-oppgave # value is the secret name in Google Secret Manager
  azure:
    application:
      enabled: true
    #oppgave_clientid: dev-fss.oppgavehandtering.oppgave
  accessPolicy:
    outbound:
      external:
        - host: oppgave.dev-fss-pub.nais.io
        - host: eessi-pensjon-journalforing-q1.intern.dev.nav.no
        - host: saf-q2.dev-fss-pub.nais.io

  env:
    - name: SPRING_PROFILES_ACTIVE
      value: test
    - name: ONPREM_KAFKA_BOOTSTRAP_SERVERS_URL
      value: SSL://b27apvl00045.preprod.local:8443,SSL://b27apvl00046.preprod.local:8443,SSL://b27apvl00047.preprod.local:8443
    - name: OPPGAVE_OPPGAVER_URL
      value: https://oppgave-q1.dev-fss-pub.nais.io
    - name: OPPGAVE_CLIENT_ID
      value: dev-fss.oppgavehandtering.oppgave-q1
    - name: SAF_GRAPHQL_URL
      value: https://saf-q2.dev-fss-pub.nais.io/graphql
    - name: GCP_BUCKET_NAME
      value: eessi-pensjon-oppgave-q1
    - name: GCP_STORAGE_API_URL
      value: https://storage.googleapis.com
    - name: KAFKA_OPPGAVE_TOPIC
      value: eessipensjon.privat-oppgave-q1
    - name: AZURE_APP_SAF_CLIENT_ID
      value: dev-fss.teamdokumenthandtering.saf

  gcp:
    buckets:
      - name: eessi-pensjon-oppgave-q1
        retentionPeriodDays: 30
        lifecycleCondition:
          age: 7
          createdBefore: 2020-01-01
          numNewerVersions: 2
          withState: ANY
        uniformBucketLevelAccess: true

  image: {{ image }}
  liveness:
    path: /internal/isalive
    port: 8080
    initialDelay: 20
  port: 8080
  prometheus:
    enabled: true
    path: /actuator/prometheus
  readiness:
    path: /internal/isready
    port: 8080
    initialDelay: 20
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: 4000m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 512Mi