kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: eessi-pensjon-oppgave-q2
  namespace: eessipensjon
  labels:
    team: eessipensjon
spec:
  kafka:
    pool: nav-dev
  envFrom:
    - secret: eessi-pensjon-oppgave # value is the secret name in Google Secret Manager
  azure:
    application:
      enabled: true
    #oppgave_clientid: dev-fss.oppgavehandtering.oppgave
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: test
    - name: ONPREM_KAFKA_BOOTSTRAP_SERVERS_URL
      value: SSL://b27apvl00045.preprod.local:8443,SSL://b27apvl00046.preprod.local:8443,SSL://b27apvl00047.preprod.local:8443
    - name: OPPGAVE_OPPGAVER_URL
      value: https://oppgave.dev-fss-pub.nais.io/api/v1/oppgaver
    - name: OPPGAVE_CLIENT_ID
      value: dev-fss.oppgavehandtering.oppgave
#      value: 41ca50ba-e44f-4bc8-9e31-b745a0041926
    - name: KAFKA_OPPGAVE_TOPIC
      value: eessipensjon.privat-oppgave-q2
  image: {{ image }}
  liveness:
    path: /internal/isalive
    port: 8080
    initialDelay: 20
  port: 8080
  prometheus:
    enabled: true
    path: /actuator/prometheus
  readiness:
    path: /internal/isready
    port: 8080
    initialDelay: 20
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: 2000m
      memory: 1Gi
    requests:
      cpu: 400m
      memory: 1Gi