name: Deploy topics

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'src/**'
jobs:
  deploy_topics:
    name: 'Deploy topics'
    runs-on: ubuntu-latest
    steps:
      - name: 'Pull repo'
        uses: actions/checkout@v3

      - name: 'Deploy privat-oppgave-q2 to eessipensjon namespace'
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: nais/topics/topic-privat-oppgave-q2.yaml

      - name: 'Deploy privat-oppdater-oppgave-q2 to eessipensjon namespace'
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: nais/topics/topic-privat-oppdater-oppgave-q2.yaml

      - name: 'Deploy privat-oppgave to eessipensjon namespace'
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-gcp
          RESOURCE: nais/topics/topic-privat-oppgave.yaml